builds:
  - id: "windows"
    main: ./cmd/main.go
    goos: [windows]
    goarch: [amd64]
    ldflags:
      - -X 'internal/core.version={{ .Version }}'
      - -H=windowsgui

  - id: "linux-darwin"
    main: ./cmd/main.go
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -X 'internal/core.version={{ .Version }}'
