name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please check if a issue already exists for your problem
      options:
        - label: I have checked the existing issues
          required: true

  - type: textarea
    attributes:
      label: Describe your issue
      description: A clear and concise description of your issue.
    validations:
      required: true
